name: 'Tests: node.js (v10 - v11)'

on: [pull_request, push]

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.set-matrix.outputs.requireds }}
      minors: ${{ steps.set-matrix.outputs.optionals }}
    steps:
      - uses: ljharb/actions/node/matrix@main
        id: set-matrix
        with:
          versionsAsRoot: true
          preset: '^10 || ^11'

  latest:
    needs: [matrix]
    name: 'latest minors'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: ${{ fromJson(needs.matrix.outputs.latest) }}
        command:
          - test:stock
          - test:staging
          - test:shams:corejs
          - test:shams:getownpropertysymbols

    steps:
      - uses: actions/checkout@v4
      - uses: ljharb/actions/node/install@main
        name: 'nvm install ${{ matrix.node-version }} && npm install'
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run ${{ matrix.command }}
      - uses: codecov/codecov-action@v3.1.5

  minors:
    needs: [matrix, latest]
    name: 'non-latest minors'
    continue-on-error: true
    if: ${{ !github.head_ref || !startsWith(github.head_ref, 'renovate') }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: ${{ fromJson(needs.matrix.outputs.minors) }}
        command:
          - test:stock
          - test:staging
          - test:shams:corejs
          - test:shams:getownpropertysymbols

    steps:
      - uses: actions/checkout@v4
      - uses: ljharb/actions/node/install@main
        name: 'nvm install ${{ matrix.node-version }} && npm install'
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run ${{ matrix.command }}
      - uses: codecov/codecov-action@v3.1.5

  node:
    name: 'node v10 - v11'
    needs: [latest, minors]
    runs-on: ubuntu-latest
    steps:
      - run: true
